// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfqewnziiuzzkpfimwlx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmcWV3bnppaXV6emtwZmltd2x4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNTgyNDAsImV4cCI6MjA2NjYzNDI0MH0.qhTePjunvo0pK21xuX8ehSnAdOiNIC8bV1xLDW1udIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});